export const BankList = [
    {
        id:1,
        bank_name:'HBC은행',
        status:0
    },
    {
        id:2,
        bank_name:'SB저축은행',
        status:1
    },
    {
        id:3,
        bank_name:'SC제일은행',
        status:0
    },
    {
        id:4,
        bank_name:'경남은행',
        status:1
    },
    {
        id:5,
        bank_name:'광주은행',
        status:1
    },
    {
        id:6,
        bank_name:'국민',
        status:1
    },
    {
        id:7,
        bank_name:'기업은행',
        status:1
    },
    {
        id:8,
        bank_name:'농협은행',
        status:1
    },
]