export const domaiData = [
    {
        id:1,
        domain_name:'cn-9797.com',
        setting:[
            {
                setting_name:'전화번호',
                setting_method:'phone_number',
                value:'0938-092-000'
            },
            {
                setting_name:'전화번호 링크',
                setting_method:'phone_number_link',
                value:''
            },
            {
                setting_name:'텔레그램',
                setting_method:'telegram',
                value:''
            },
            {
                setting_name:'카톡',
                setting_method:'telegram_link',
                value:''
            },
            {
                setting_name:'텔레그램 링크',
                setting_method:'kakao_talk',
                value:'00333'
            },
            {
                setting_name:'카톡 링크',
                setting_method:'takaotalk_link',
                value:''
            },
        ]
    },
    {
        id:2,
        domain_name:'cw364.com',
        setting:[
            {
                setting_name:'전화번호',
                setting_method:'phone_number',
                value:'112-333-345'
            },
            {
                setting_name:'전화번호 링크',
                setting_method:'phone_number_link',
                value:''
            },
            {
                setting_name:'텔레그램',
                setting_method:'telegram',
                value:''
            },
            {
                setting_name:'카톡',
                setting_method:'telegram_link',
                value:''
            },
            {
                setting_name:'텔레그램 링크',
                setting_method:'kakao_talk',
                value:'00333'
            },
            {
                setting_name:'카톡 링크',
                setting_method:'takaotalk_link',
                value:''
            },
        ]
    },
    {
        id:3,
        domain_name:'thernthy.com',
        setting:[
            {
                setting_name:'전화번호',
                setting_method:'phone_number',
                value:'112-333-345'
            },
            {
                setting_name:'전화번호 링크',
                setting_method:'phone_number_link',
                value:''
            },
            {
                setting_name:'텔레그램',
                setting_method:'telegram',
                value:''
            },
            {
                setting_name:'카톡',
                setting_method:'telegram_link',
                value:''
            },
            {
                setting_name:'텔레그램 링크',
                setting_method:'kakao_talk',
                value:'00333'
            },
            {
                setting_name:'카톡 링크',
                setting_method:'takaotalk_link',
                value:''
            },
        ]
    },
    {
        id:4,
        domain_name:'demo2.com',
        setting:[
            {
                setting_name:'전화번호',
                setting_method:'phone_number',
                value:'112-333-345'
            },
            {
                setting_name:'전화번호 링크',
                setting_method:'phone_number_link',
                value:''
            },
            {
                setting_name:'텔레그램',
                setting_method:'telegram',
                value:''
            },
            {
                setting_name:'카톡',
                setting_method:'telegram_link',
                value:''
            },
            {
                setting_name:'텔레그램 링크',
                setting_method:'kakao_talk',
                value:'736-093'
            },
            {
                setting_name:'카톡 링크',
                setting_method:'takaotalk_link',
                value:''
            },
        ]
    },
    {
        id:5,
        domain_name:'demo2.com',
        setting:[
            {
                setting_name:'전화번호',
                setting_method:'phone_number',
                value:'112-333-345'
            },
            {
                setting_name:'전화번호 링크',
                setting_method:'phone_number_link',
                value:''
            },
            {
                setting_name:'텔레그램',
                setting_method:'telegram',
                value:''
            },
            {
                setting_name:'카톡',
                setting_method:'telegram_link',
                value:''
            },
            {
                setting_name:'텔레그램 링크',
                setting_method:'kakao_talk',
                value:'736-093'
            },
            {
                setting_name:'카톡 링크',
                setting_method:'takaotalk_link',
                value:''
            },
        ]
    },
    {
        id:7,
        domain_name:'demo2.com',
        setting:[
            {
                setting_name:'전화번호',
                setting_method:'phone_number',
                value:'112-333-345'
            },
            {
                setting_name:'전화번호 링크',
                setting_method:'phone_number_link',
                value:''
            },
            {
                setting_name:'텔레그램',
                setting_method:'telegram',
                value:''
            },
            {
                setting_name:'카톡',
                setting_method:'telegram_link',
                value:''
            },
            {
                setting_name:'텔레그램 링크',
                setting_method:'kakao_talk',
                value:'736-093'
            },
            {
                setting_name:'카톡 링크',
                setting_method:'takaotalk_link',
                value:''
            },
        ]
    },
]