
export const RowData = [
    {
        index: 1,
        site: "Site A",
        root_distributor: "Root Dist A",
        top_distributor: "Top Dist A",
        id: "ABC123",
        nickname: "User1",
        account_holder: "Account Holder 1",
        color_nickname: "Blue",
        date_of_subscription: new Date("2023-01-15"),
        number_of_failures: "2",
        block_date_and_time: new Date("2024-04-30T12:00:00"),
        explanation: "Failed to meet requirements",
      },
      {
        index: 2,
        site: "Site B",
        root_distributor: "Root Dist B",
        top_distributor: "Top Dist B",
        id: "DEF456",
        nickname: "User2",
        account_holder: "Account Holder 2",
        color_nickname: "Red",
        date_of_subscription: new Date("2022-11-20"),
        number_of_failures: "0",
        block_date_and_time: new Date("2024-05-01T09:30:00"),
        explanation: "Unauthorized access",
      },
      {
        index: 3,
        site: "Site C",
        root_distributor: "Root Dist C",
        top_distributor: "Top Dist C",
        id: "GHI789",
        nickname: "User3",
        account_holder: "Account Holder 3",
        color_nickname: "Green",
        date_of_subscription: new Date("2023-05-10"),
        number_of_failures: "1",
        block_date_and_time: new Date("2024-04-28T15:45:00"),
        explanation: "Security breach",
      },
      {
        index: 4,
        site: "Site D",
        root_distributor: "Root Dist D",
        top_distributor: "Top Dist D",
        id: "JKL012",
        nickname: "User4",
        account_holder: "Account Holder 4",
        color_nickname: "Yellow",
        date_of_subscription: new Date("2023-02-28"),
        number_of_failures: "3",
        block_date_and_time: new Date("2024-04-29T10:20:00"),
        explanation: "Policy violation",
      },
      {
        index: 5,
        site: "Site E",
        root_distributor: "Root Dist E",
        top_distributor: "Top Dist E",
        id: "MNO345",
        nickname: "User5",
        account_holder: "Account Holder 5",
        color_nickname: "Purple",
        date_of_subscription: new Date("2023-07-05"),
        number_of_failures: "0",
        block_date_and_time: new Date("2024-04-27T08:00:00"),
        explanation: "None",
      },
      {
        index: 6,
        site: "Site F",
        root_distributor: "Root Dist F",
        top_distributor: "Top Dist F",
        id: "PQR678",
        nickname: "User6",
        account_holder: "Account Holder 6",
        color_nickname: "Orange",
        date_of_subscription: new Date("2023-04-18"),
        number_of_failures: "1",
        block_date_and_time: new Date("2024-05-02T14:10:00"),
        explanation: "Account compromise",
      },
      {
        index: 7,
        site: "Site G",
        root_distributor: "Root Dist G",
        top_distributor: "Top Dist G",
        id: "STU901",
        nickname: "User7",
        account_holder: "Account Holder 7",
        color_nickname: "Cyan",
        date_of_subscription: new Date("2023-08-30"),
        number_of_failures: "0",
        block_date_and_time: new Date("2024-04-30T16:30:00"),
        explanation: "Suspicious activity",
      },
      {
        index: 8,
        site: "Site H",
        root_distributor: "Root Dist H",
        top_distributor: "Top Dist H",
        id: "VWX234",
        nickname: "User8",
        account_holder: "Account Holder 8",
        color_nickname: "Magenta",
        date_of_subscription: new Date("2023-06-12"),
        number_of_failures: "2",
        block_date_and_time: new Date("2024-05-01T11:45:00"),
        explanation: "Data breach",
      },
      {
        index: 9,
        site: "Site I",
        root_distributor: "Root Dist I",
        top_distributor: "Top Dist I",
        id: "YZA567",
        nickname: "User9",
        account_holder: "Account Holder 9",
        color_nickname: "Teal",
        date_of_subscription: new Date("2022-12-25"),
        number_of_failures: "1",
        block_date_and_time: new Date("2024-04-29T09:00:00"),
        explanation: "Fraudulent activity",
      },
      {
        index: 10,
        site: "Site J",
        root_distributor: "Root Dist J",
        top_distributor: "Top Dist J",
        id: "BCD890",
        nickname: "User10",
        account_holder: "Account Holder 10",
        color_nickname: "Lime",
        date_of_subscription: new Date("2023-03-08"),
        number_of_failures: "0",
        block_date_and_time: new Date("2024-05-02T13:20:00"),
        explanation: "None",
      },
      {
        index: 11,
        site: "Site K",
        root_distributor: "Root Dist K",
        top_distributor: "Top Dist K",
        id: "EFG123",
        nickname: "User11",
        account_holder: "Account Holder 11",
        color_nickname: "Brown",
        date_of_subscription: new Date("2023-09-20"),
        number_of_failures: "1",
        block_date_and_time: new Date("2024-05-03T09:50:00"),
        explanation: "Account suspension",
      },
      {
        index: 12,
        site: "Site L",
        root_distributor: "Root Dist L",
        top_distributor: "Top Dist L",
        id: "HIJ456",
        nickname: "User12",
        account_holder: "Account Holder 12",
        color_nickname: "Pink",
        date_of_subscription: new Date("2023-01-02"),
        number_of_failures: "3",
        block_date_and_time: new Date("2024-04-28T14:15:00"),
        explanation: "Security violation",
      },
      {
        index: 13,
        site: "Site M",
        root_distributor: "Root Dist M",
        top_distributor: "Top Dist M",
        id: "KLM789",
        nickname: "User13",
        account_holder: "Account Holder 13",
        color_nickname: "Indigo",
        date_of_subscription: new Date("2023-05-15"),
        number_of_failures: "0",
        block_date_and_time: new Date("2024-04-30T10:40:00"),
        explanation: "None",
      },
      {
        index: 14,
        site: "Site N",
        root_distributor: "Root Dist N",
        top_distributor: "Top Dist N",
        id: "OPQ012",
        nickname: "User14",
        account_holder: "Account Holder 14",
        color_nickname: "Gray",
        date_of_subscription: new Date("2023-07-30"),
        number_of_failures: "2",
        block_date_and_time: new Date("2024-05-01T12:05:00"),
        explanation: "Unauthorized modification",
      },
      {
        index: 15,
        site: "Site O",
        root_distributor: "Root Dist O",
        top_distributor: "Top Dist O",
        id: "RST345",
        nickname: "User15",
        account_holder: "Account Holder 15",
        color_nickname: "Silver",
        date_of_subscription: new Date("2023-03-18"),
        number_of_failures: "1",
        block_date_and_time: new Date("2024-04-29T08:20:00"),
        explanation: "Account takeover",
      },
      {
        index: 16,
        site: "Site P",
        root_distributor: "Root Dist P",
        top_distributor: "Top Dist P",
        id: "UVW678",
        nickname: "User16",
        account_holder: "Account Holder 16",
        color_nickname: "Gold",
        date_of_subscription: new Date("2023-10-05"),
        number_of_failures: "0",
        block_date_and_time: new Date("2024-05-02T15:30:00"),
        explanation: "None",
      },
      {
        index: 17,
        site: "Site Q",
        root_distributor: "Root Dist Q",
        top_distributor: "Top Dist Q",
        id: "XYZ901",
        nickname: "User17",
        account_holder: "Account Holder 17",
        color_nickname: "White",
        date_of_subscription: new Date("2022-11-15"),
        number_of_failures: "3",
        block_date_and_time: new Date("2024-04-27T11:10:00"),
        explanation: "Breach of terms",
      },
      {
        index: 18,
        site: "Site R",
        root_distributor: "Root Dist R",
        top_distributor: "Top Dist R",
        id: "234ABC",
        nickname: "User18",
        account_holder: "Account Holder 18",
        color_nickname: "Black",
        date_of_subscription: new Date("2023-08-10"),
        number_of_failures: "2",
        block_date_and_time: new Date("2024-04-30T13:50:00"),
        explanation: "Account closure",
      },
      {
        index: 19,
        site: "Site S",
        root_distributor: "Root Dist S",
        top_distributor: "Top Dist S",
        id: "567DEF",
        nickname: "User19",
        account_holder: "Account Holder 19",
        color_nickname: "Crimson",
        date_of_subscription: new Date("2023-12-01"),
        number_of_failures: "1",
        block_date_and_time: new Date("2024-05-01T09:15:00"),
        explanation: "Security incident",
      },
      {
        index: 20,
        site: "Site T",
        root_distributor: "Root Dist T",
        top_distributor: "Top Dist T",
        id: "890GHI",
        nickname: "User20",
        account_holder: "Account Holder 20",
        color_nickname: "Azure",
        date_of_subscription: new Date("2023-04-25"),
        number_of_failures: "0",
        block_date_and_time: new Date("2024-05-02T12:40:00"),
        explanation: "None",
      },
      {
        index: 21,
        site: "Site U",
        root_distributor: "Root Dist U",
        top_distributor: "Top Dist U",
        id: "JKL123",
        nickname: "User21",
        account_holder: "Account Holder 21",
        color_nickname: "Lavender",
        date_of_subscription: new Date("2023-02-12"),
        number_of_failures: "2",
        block_date_and_time: new Date("2024-04-29T14:30:00"),
        explanation: "Account breach",
      },
      {
        index: 22,
        site: "Site V",
        root_distributor: "Root Dist V",
        top_distributor: "Top Dist V",
        id: "MNO456",
        nickname: "User22",
        account_holder: "Account Holder 22",
        color_nickname: "Emerald",
        date_of_subscription: new Date("2023-09-08"),
        number_of_failures: "1",
        block_date_and_time: new Date("2024-05-03T10:00:00"),
        explanation: "Data compromise",
      },
      {
        index: 23,
        site: "Site W",
        root_distributor: "Root Dist W",
        top_distributor: "Top Dist W",
        id: "PQR789",
        nickname: "User23",
        account_holder: "Account Holder 23",
        color_nickname: "Sapphire",
        date_of_subscription: new Date("2023-11-20"),
        number_of_failures: "0",
        block_date_and_time: new Date("2024-04-28T11:20:00"),
        explanation: "None",
      },
      {
        index: 24,
        site: "Site X",
        root_distributor: "Root Dist X",
        top_distributor: "Top Dist X",
        id: "STU012",
        nickname: "User24",
        account_holder: "Account Holder 24",
        color_nickname: "Ruby",
        date_of_subscription: new Date("2023-05-30"),
        number_of_failures: "3",
        block_date_and_time: new Date("2024-04-30T13:55:00"),
        explanation: "Account hijacking",
      },
      {
        index: 25,
        site: "Site Y",
        root_distributor: "Root Dist Y",
        top_distributor: "Top Dist Y",
        id: "VWX345",
        nickname: "User25",
        account_holder: "Account Holder 25",
        color_nickname: "Amber",
        date_of_subscription: new Date("2023-03-25"),
        number_of_failures: "1",
        block_date_and_time: new Date("2024-05-01T08:40:00"),
        explanation: "Unauthorized access",
      },
      {
        index: 26,
        site: "Site Z",
        root_distributor: "Root Dist Z",
        top_distributor: "Top Dist Z",
        id: "YZA678",
        nickname: "User26",
        account_holder: "Account Holder 26",
        color_nickname: "Turquoise",
        date_of_subscription: new Date("2023-06-18"),
        number_of_failures: "0",
        block_date_and_time: new Date("2024-05-02T11:45:00"),
        explanation: "None",
      },
      {
        index: 27,
        site: "Site AA",
        root_distributor: "Root Dist AA",
        top_distributor: "Top Dist AA",
        id: "BCD901",
        nickname: "User27",
        account_holder: "Account Holder 27",
        color_nickname: "Pearl",
        date_of_subscription: new Date("2023-08-05"),
        number_of_failures: "2",
        block_date_and_time: new Date("2024-04-29T12:10:00"),
        explanation: "Account termination",
      },
      {
        index: 28,
        site: "Site AB",
        root_distributor: "Root Dist AB",
        top_distributor: "Top Dist AB",
        id: "EFG234",
        nickname: "User28",
        account_holder: "Account Holder 28",
        color_nickname: "Diamond",
        date_of_subscription: new Date("2023-10-12"),
        number_of_failures: "1",
        block_date_and_time: new Date("2024-05-03T09:25:00"),
        explanation: "Security compromise",
      },
      {
        index: 29,
        site: "Site AC",
        root_distributor: "Root Dist AC",
        top_distributor: "Top Dist AC",
        id: "HIJ567",
        nickname: "User29",
        account_holder: "Account Holder 29",
        color_nickname: "Opal",
        date_of_subscription: new Date("2023-02-28"),
        number_of_failures: "0",
        block_date_and_time: new Date("2024-04-27T08:50:00"),
        explanation: "None",
      },
      {
        index: 30,
        site: "Site AD",
        root_distributor: "Root Dist AD",
        top_distributor: "Top Dist AD",
        id: "KLM890",
        nickname: "User30",
        account_holder: "Account Holder 30",
        color_nickname: "Onyx",
        date_of_subscription: new Date("2023-12-20"),
        number_of_failures: "3",
        block_date_and_time: new Date("2024-04-28T12:30:00"),
        explanation: "Unauthorized activity",
      },
]